apiVersion: di.io/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application-sample
  name: application-sample
  namespace: team-demo
spec:
  image: tempregistrydi.azurecr.io/controller:c9a94719ddef2fe47ac72c22deb53045fb5ff4b7
  port: 8080
  replicas: 2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
