name: Build and Push Docker Image to ACR

on:
  workflow_dispatch: 

env:
  ACR_REGISTRY: tempregistrydi.azurecr.io
  IMAGE_NAME: controller
  IMAGE_TAG: ${{ github.sha }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.ACR_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Push Docker Image
      run: docker push ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Output Image Name
      run: 'echo "Docker Image pushed: ${{ env.ACR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"'

